name: 🐛 Bug Report
description: Report a Bork
title: "[🐛 Bug]: "
labels: ["🐞Bork", "triage"]
assignees:
  - BehrRiley
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share this bork! 
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: A clear description of what the issue is or what it's causing to happen
      placeholder: what happened?
      value: "A thing did a bork!"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How To Reproduce
      description: Provide how to reproduce the issue, or explain how you found it
      placeholder: Tell us what you see!
      value:
        | 
          Example:
          Steps to reproduce the bug:
          1. Prepare to do '...'
          2. Go to '...' / Click on '...' / Scroll down to '...'
          3. ???
          4. See error
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen, and what actually happened
      placeholder: I tried to eat my sandwich and my dog got sick.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      multiple: true
      description: What client are you on?
      options:
        - Vanilla
        - Optifine
        - Fabric
        - Forge
        - A hacking client teehee
        - Something else
      default: 0
    validations:
      required: true
  - type: textarea
    id: screenies
    attributes:
      label: Screenshots or clips
      description: If able, please share any screenshots, videoes, or media that help show what's happening
      render: java
  - type: textarea
    id: client_logs
    attributes:
      label: Client log output
      description: Please copy and paste any relevant log output if this is resource pack or datapack related. This will be automatically formatted into code, so no need for backticks.
      render: java
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree this wasn't created to waste our time
      options:
        - label: This is not a waste of your time to review.
          required: true
